AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for robot

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  RobotHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  RPAValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./validator/
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /robot/dryrun
            Method: POST
            ApiId: !Ref RobotHttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./validator
      DockerTag: python3.9-validator

Outputs:
  RobotHttpApi:
    Description: Serverless HTTP API (API Gateway endpoint URL)
    Value: !Sub "https://${RobotHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
